name: "Auto Assign"
on:
  pull_request:
    branches:
      - master
      - develop
      - "release/**"
    types: [opened]

jobs:
  add-reviewers:
    name: "Auto assign reviewers"
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
