name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm publish on every push
      uses: shawnbot/npm-publish-action@v1.0.1
