name: Publish to Github Packages
on:
  push:
    branches:
      - feature/deploy-to-github-packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install dependencies
      run: npm install
    - name: Publish to Github Packages
      run: npm publish
